name: blogapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  get_it: ^9.2.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  supabase: ^2.10.2
  supabase_flutter: ^2.12.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
